name: instagram_clone
description: Instagram clone with flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.13.0+1
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^0.15.2
  # https://pub.dev/packages/firebase_storage
  firebase_storage: ^3.1.0
  # https://pub.dev/packages/firebase_database
  firebase_database: ^3.1.1
  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^4.0.14
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^2.1.1
  # https://pub.dev/packages/equatable
  equatable: ^1.0.1
  # https://pub.dev/packages/meta
  meta: ^1.1.7
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.5.0
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^0.1.3
  # https://pub.dev/packages/image_picker
  image_picker: ^0.6.2+1
  # https://pub.dev/packages/image_cropper
  image_cropper: ^1.0.2
  # https://pub.dev/packages/uuid
  uuid: ^2.0.4
  # https://pub.dev/packages/toast
  toast: ^0.1.5
  # https://pub.dev/packages/http
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/img/
